package frc.robot.subsystems.manipulator;

public enum ManipulatorState {
    PREPARE_IDLE,
    WAIT_IDLE,
    IDLE(),
    PREPARE_L1(),
    WAIT_L1(),
    L1(),
    PREPARE_L2(),
    WAIT_L2(),
    L2(),
    PREPARE_L3(),
    WAIT_L3(),
    L3(),
    PREPARE_L4(),
    WAIT_L4(),
    L4(),
    PREPARE_CAPPED_L4(),
    WAIT_CAPPED_L4(),
    CAPPED_L4(),
    PREPARE_CORAL_STATION(),
    WAIT_CORAL_STATION(),
    CORAL_STATION(),
}
